# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_MainWindows.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 546)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 950, 23))
        self.menubar.setObjectName("menubar")
        self.Main_menu_file = QtWidgets.QMenu(self.menubar)
        self.Main_menu_file.setObjectName("Main_menu_file")
        self.Main_menu_edit = QtWidgets.QMenu(self.menubar)
        self.Main_menu_edit.setObjectName("Main_menu_edit")
        self.Main_menu_view = QtWidgets.QMenu(self.menubar)
        self.Main_menu_view.setObjectName("Main_menu_view")
        self.Main_menu_draw = QtWidgets.QMenu(self.menubar)
        self.Main_menu_draw.setObjectName("Main_menu_draw")
        self.Main_menu_SAGD = QtWidgets.QMenu(self.menubar)
        self.Main_menu_SAGD.setObjectName("Main_menu_SAGD")
        self.Main_menu_tool = QtWidgets.QMenu(self.menubar)
        self.Main_menu_tool.setObjectName("Main_menu_tool")
        self.Main_menu_help = QtWidgets.QMenu(self.menubar)
        self.Main_menu_help.setObjectName("Main_menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_file_add = QtWidgets.QAction(MainWindow)
        self.action_file_add.setObjectName("action_file_add")
        self.actiondakai = QtWidgets.QAction(MainWindow)
        self.actiondakai.setObjectName("actiondakai")
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("action_about")
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_SAGD_load_data = QtWidgets.QAction(MainWindow)
        self.action_SAGD_load_data.setObjectName("action_SAGD_load_data")
        self.action__SAGD_calculate = QtWidgets.QAction(MainWindow)
        self.action__SAGD_calculate.setObjectName("action__SAGD_calculate")
        self.action_SAGD_output_imgs = QtWidgets.QAction(MainWindow)
        self.action_SAGD_output_imgs.setObjectName("action_SAGD_output_imgs")
        self.action_add_basic_para1 = QtWidgets.QAction(MainWindow)
        self.action_add_basic_para1.setObjectName("action_add_basic_para1")
        self.actionjibencanshu2 = QtWidgets.QAction(MainWindow)
        self.actionjibencanshu2.setObjectName("actionjibencanshu2")
        self.action_SAGD_add_paras = QtWidgets.QAction(MainWindow)
        self.action_SAGD_add_paras.setObjectName("action_SAGD_add_paras")
        self.Main_menu_file.addAction(self.action_file_add)
        self.Main_menu_file.addAction(self.actiondakai)
        self.Main_menu_SAGD.addAction(self.action_SAGD_add_paras)
        self.Main_menu_SAGD.addAction(self.action_SAGD_load_data)
        self.Main_menu_SAGD.addSeparator()
        self.Main_menu_SAGD.addAction(self.action__SAGD_calculate)
        self.Main_menu_SAGD.addSeparator()
        self.Main_menu_SAGD.addAction(self.action_SAGD_output_imgs)
        self.Main_menu_help.addAction(self.action_about)
        self.menubar.addAction(self.Main_menu_file.menuAction())
        self.menubar.addAction(self.Main_menu_edit.menuAction())
        self.menubar.addAction(self.Main_menu_view.menuAction())
        self.menubar.addAction(self.Main_menu_draw.menuAction())
        self.menubar.addAction(self.Main_menu_SAGD.menuAction())
        self.menubar.addAction(self.Main_menu_tool.menuAction())
        self.menubar.addAction(self.Main_menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Main_menu_file.setTitle(_translate("MainWindow", "文件"))
        self.Main_menu_edit.setTitle(_translate("MainWindow", "编辑"))
        self.Main_menu_view.setTitle(_translate("MainWindow", "视图"))
        self.Main_menu_draw.setTitle(_translate("MainWindow", "绘图"))
        self.Main_menu_SAGD.setTitle(_translate("MainWindow", "SAGD"))
        self.Main_menu_tool.setTitle(_translate("MainWindow", "工具"))
        self.Main_menu_help.setTitle(_translate("MainWindow", "帮助"))
        self.action_file_add.setText(_translate("MainWindow", "新建"))
        self.actiondakai.setText(_translate("MainWindow", "dakai"))
        self.action_about.setText(_translate("MainWindow", "关于"))
        self.action.setText(_translate("MainWindow", "加载参数"))
        self.action_SAGD_load_data.setText(_translate("MainWindow", "载入SAGD数据"))
        self.action__SAGD_calculate.setText(_translate("MainWindow", "蒸汽腔计算"))
        self.action_SAGD_output_imgs.setText(_translate("MainWindow", "导出图形"))
        self.action_add_basic_para1.setText(_translate("MainWindow", "基本参数"))
        self.actionjibencanshu2.setText(_translate("MainWindow", "jibencanshu2"))
        self.action_SAGD_add_paras.setText(_translate("MainWindow", "设置参数"))

