# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_thermophysical_para.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Widget_Thermophysical_paras(object):
    def setupUi(self, Widget_Thermophysical_paras):
        Widget_Thermophysical_paras.setObjectName("Widget_Thermophysical_paras")
        Widget_Thermophysical_paras.resize(585, 406)
        self.groupBox_Oil_pool_paras = QtWidgets.QGroupBox(Widget_Thermophysical_paras)
        self.groupBox_Oil_pool_paras.setGeometry(QtCore.QRect(60, 20, 481, 311))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(12)
        self.groupBox_Oil_pool_paras.setFont(font)
        self.groupBox_Oil_pool_paras.setObjectName("groupBox_Oil_pool_paras")
        self.lineEdit_Cot = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_Cot.setGeometry(QtCore.QRect(220, 30, 71, 21))
        self.lineEdit_Cot.setObjectName("lineEdit_Cot")
        self.label = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label.setGeometry(QtCore.QRect(120, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_Cop = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_Cop.setGeometry(QtCore.QRect(220, 70, 71, 21))
        self.lineEdit_Cop.setObjectName("lineEdit_Cop")
        self.label_12 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_12.setGeometry(QtCore.QRect(130, 70, 81, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_9 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_9.setGeometry(QtCore.QRect(300, 110, 71, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_10.setGeometry(QtCore.QRect(140, 110, 61, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.lineEdit_Alf = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_Alf.setGeometry(QtCore.QRect(220, 110, 71, 21))
        self.lineEdit_Alf.setObjectName("lineEdit_Alf")
        self.lineEdit_Rumdacap = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_Rumdacap.setGeometry(QtCore.QRect(220, 150, 71, 21))
        self.lineEdit_Rumdacap.setObjectName("lineEdit_Rumdacap")
        self.label_13 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_13.setGeometry(QtCore.QRect(130, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_14.setGeometry(QtCore.QRect(300, 150, 71, 21))
        self.label_14.setObjectName("label_14")
        self.lineEdit_Mcap = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_Mcap.setGeometry(QtCore.QRect(220, 190, 71, 21))
        self.lineEdit_Mcap.setObjectName("lineEdit_Mcap")
        self.label_15 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_15.setGeometry(QtCore.QRect(150, 190, 51, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_16.setGeometry(QtCore.QRect(300, 190, 71, 21))
        self.label_16.setObjectName("label_16")
        self.lineEdit_CrTs = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_CrTs.setGeometry(QtCore.QRect(220, 230, 71, 21))
        self.lineEdit_CrTs.setObjectName("lineEdit_CrTs")
        self.label_17 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_17.setGeometry(QtCore.QRect(40, 230, 171, 21))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_18.setGeometry(QtCore.QRect(300, 230, 71, 21))
        self.label_18.setObjectName("label_18")
        self.lineEdit_m = QtWidgets.QLineEdit(self.groupBox_Oil_pool_paras)
        self.lineEdit_m.setGeometry(QtCore.QRect(220, 270, 71, 21))
        self.lineEdit_m.setObjectName("lineEdit_m")
        self.label_19 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_19.setGeometry(QtCore.QRect(300, 270, 71, 21))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_Oil_pool_paras)
        self.label_20.setGeometry(QtCore.QRect(160, 270, 51, 16))
        font = QtGui.QFont()
        font.setFamily("SimSun-ExtB")
        font.setPointSize(9)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.widget = QtWidgets.QWidget(Widget_Thermophysical_paras)
        self.widget.setGeometry(QtCore.QRect(110, 350, 336, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Thermophysical_LastStep = QtWidgets.QPushButton(self.widget)
        self.pushButton_Thermophysical_LastStep.setObjectName("pushButton_Thermophysical_LastStep")
        self.horizontalLayout.addWidget(self.pushButton_Thermophysical_LastStep)
        self.pushButton_oil_para_load = QtWidgets.QPushButton(self.widget)
        self.pushButton_oil_para_load.setObjectName("pushButton_oil_para_load")
        self.horizontalLayout.addWidget(self.pushButton_oil_para_load)
        self.pushButton_oil_para_finish = QtWidgets.QPushButton(self.widget)
        self.pushButton_oil_para_finish.setObjectName("pushButton_oil_para_finish")
        self.horizontalLayout.addWidget(self.pushButton_oil_para_finish)
        self.pushButton_oil_para_next = QtWidgets.QPushButton(self.widget)
        self.pushButton_oil_para_next.setObjectName("pushButton_oil_para_next")
        self.horizontalLayout.addWidget(self.pushButton_oil_para_next)

        self.retranslateUi(Widget_Thermophysical_paras)
        QtCore.QMetaObject.connectSlotsByName(Widget_Thermophysical_paras)

    def retranslateUi(self, Widget_Thermophysical_paras):
        _translate = QtCore.QCoreApplication.translate
        Widget_Thermophysical_paras.setWindowTitle(_translate("Widget_Thermophysical_paras", "基础参数1"))
        self.groupBox_Oil_pool_paras.setTitle(_translate("Widget_Thermophysical_paras", "热物性参数"))
        self.label.setText(_translate("Widget_Thermophysical_paras", "原油热膨胀系数"))
        self.label_12.setText(_translate("Widget_Thermophysical_paras", "原油压缩系数"))
        self.label_9.setText(_translate("Widget_Thermophysical_paras", "m^2/d"))
        self.label_10.setText(_translate("Widget_Thermophysical_paras", "热扩散系数"))
        self.label_13.setText(_translate("Widget_Thermophysical_paras", "盖层导热系数"))
        self.label_14.setText(_translate("Widget_Thermophysical_paras", "kg/m^3"))
        self.label_15.setText(_translate("Widget_Thermophysical_paras", "盖层热容"))
        self.label_16.setText(_translate("Widget_Thermophysical_paras", "MPa"))
        self.label_17.setText(_translate("Widget_Thermophysical_paras", "饱和蒸汽抽产温度下岩石的比热"))
        self.label_18.setText(_translate("Widget_Thermophysical_paras", "J/(kg.C)"))
        self.label_19.setText(_translate("Widget_Thermophysical_paras", "无量纲"))
        self.label_20.setText(_translate("Widget_Thermophysical_paras", "粘温系数"))
        self.pushButton_Thermophysical_LastStep.setText(_translate("Widget_Thermophysical_paras", "上一步"))
        self.pushButton_oil_para_load.setText(_translate("Widget_Thermophysical_paras", "读入参数"))
        self.pushButton_oil_para_finish.setText(_translate("Widget_Thermophysical_paras", "完成"))
        self.pushButton_oil_para_next.setText(_translate("Widget_Thermophysical_paras", "下一步"))

